jobs:
    include:
      - language: csharp
        mono: none
        dotnet: 2.1.502
        solution: Validator.sln
        before_script:
            - cd Validator
        script:
            - dotnet restore
            - dotnet build
            - choco install opencover.portable
            - choco install codecov
            - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\UnitTests\bin\Debug\netcoreapp2.1\UnitTests.dll -noshadow" -filter:"+[Validator*]* -[UnitTests*]*" -output:".\Validator_Coverage.xml"
            - codecov -f "Validator_Coverage.xml"

      - language: objective-c
        os: osx
        rvm:
        - 2.2         #see before_install for getting RVM stable.
        
        env:
        - TRAVIS_TAG="Deploy-main" PROJECT_NAME="BivalenceWorld" UNITY_PROJECT_PATH="BivalenceWorld" DEPLOY_UNITYPACKAGE="path set in deploy script"
        
        
        cache:
        directories:
            - $UNITY_DOWNLOAD_CACHE
        
            
        before_install:
        - chmod a+x ./travis-build/*.sh
        
        install:
        - cat /etc/hosts
        - ./travis-build/install-unity.sh
        
        script:
        - ./travis-build/build.sh
        - ./travis-build/run-tests.sh
        
        after_success:
        - ./travis-build/export-unity-package.sh
        
        before_deploy:
        - DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"
        
        deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: $DEPLOY_UNITYPACKAGE
        skip_cleanup: true
        overwrite: true
        on:
            tags: true 
        